version: "3.7"

services:
  postgres:
    container_name: "to-do-postgres"
    image: 'postgres:11.2'
    restart: always
    ports:
      - '5432:5432'
    environment:
      - 'POSTGRES_USER=username'
      - 'POSTGRES_DB=to_do'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
  redis:
    container_name: 'to-do-redis'
    image: 'redis:5.0.5'
    ports:
      - '6379:6379'
